"""
MediKiosk v4 — Unified Patient Record Schema

Evolved for the dynamic schema-driven architecture:
  - Demographics (name, age, sex) collected at start
  - Dynamic schema stored per-encounter (generated by Stage 1)
  - Filled-state as the source of truth (not per-section SectionData)
  - Unified conversation history (not partitioned by FSM section)
  - Per-field provenance {value, confidence, source}
"""

from __future__ import annotations
from typing import Any, Optional
from pydantic import BaseModel, Field
import uuid
import time


class SlotValue(BaseModel):
    """A single clinical data point with provenance."""
    value: Any = None
    confidence: Optional[float] = None
    source: Optional[str] = None  # "direct", "conversation", "document:doc_1"


class FilledField(BaseModel):
    """A single filled field in the dynamic schema."""
    value: Any = None
    confidence: float = 0.0
    source: str = "conversation"
    filled_at_turn: int = 0


class SectionData(BaseModel):
    """
    Kept for backward-compatibility with document extraction and summary screen.
    In v4, conversation is unified, but we still store section-level summaries.
    """
    extracted: dict[str, SlotValue] = Field(default_factory=dict)
    conversation: list[dict] = Field(default_factory=list)
    turn_count: int = 0
    summary: str = ""
    is_complete: bool = False

    def add_message(self, role: str, content: str):
        self.conversation.append({"role": role, "content": content})

    def add_extracted(self, key: str, value: Any, confidence: float = 0.8, source: str = "conversation"):
        self.extracted[key] = SlotValue(value=value, confidence=confidence, source=source)

    def get_extracted_dict(self) -> dict:
        return {k: v.value for k, v in self.extracted.items() if v.value is not None}


# Keep TemplateSlots for backward compatibility (document extraction)
class TemplateSlots(BaseModel):
    template_name: str = ""
    slots: dict[str, SlotValue] = Field(default_factory=dict)

    def fill_slot(self, slot_id: str, value: Any, confidence: float, source: str):
        self.slots[slot_id] = SlotValue(value=value, confidence=confidence, source=source)


class DocumentExtraction(BaseModel):
    doc_id: str
    doc_type: str = "unknown"
    ocr_path: str = "printed"
    entities: dict = Field(default_factory=dict)


class Contradiction(BaseModel):
    field: str
    conversation_value: Any
    document_value: Any
    status: str = "unresolved_flag_for_physician"


class RedFlagEntry(BaseModel):
    rule_id: str
    description: str
    triggered_at: float = Field(default_factory=time.time)
    slot_values: dict[str, Any] = Field(default_factory=dict)


class PatientRecord(BaseModel):
    """The backbone schema — v4 with dynamic schema-driven interview."""
    session_id: str = Field(default_factory=lambda: f"sess_{uuid.uuid4().hex[:8]}")
    clinic_mode: str = "allopathic"
    macro_state: str = "INIT"
    language: str = "en-IN"

    # ── Demographics (collected at start) ──
    patient_name: str = ""
    patient_age: Optional[int] = None
    patient_sex: str = ""  # "male", "female", "other"

    # ── Chief complaint ──
    chief_complaint: SlotValue = Field(default_factory=SlotValue)
    complaint_category: Optional[str] = None

    # ── Dynamic schema (Stage 1 output) ──
    dynamic_schema: Optional[dict] = None  # The generated schema for this encounter

    # ── Filled state (Stage 2 source of truth) ──
    filled_state: dict[str, dict] = Field(default_factory=dict)
    # Shape: {field_id: {"value": ..., "confidence": 0.0-1.0}}

    # ── Unified conversation history ──
    conversation_history: list[dict] = Field(default_factory=list)
    # [{role: "assistant"|"patient", content: "...", turn: N, category: "HPI"}]
    interview_turn_count: int = 0

    # ── Legacy section data (for summary screen grouping) ──
    hpi: SectionData = Field(default_factory=SectionData)
    pmh: SectionData = Field(default_factory=SectionData)
    psh: SectionData = Field(default_factory=SectionData)
    drug_allergy: SectionData = Field(default_factory=SectionData)
    family_hx: SectionData = Field(default_factory=SectionData)
    social_hx: SectionData = Field(default_factory=SectionData)
    ros: SectionData = Field(default_factory=SectionData)
    ayush_assessment: SectionData = Field(default_factory=SectionData)

    # ── Document intelligence ──
    document_extractions: list[DocumentExtraction] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)

    # ── Safety ──
    red_flags: list[RedFlagEntry] = Field(default_factory=list)

    # ── Notes ──
    clinician_notes: list[str] = Field(default_factory=list)

    def get_section(self, section: str) -> SectionData:
        """Get the SectionData for a given macro-FSM section (legacy compat)."""
        section_map = {
            "HPI": self.hpi,
            "PMH": self.pmh,
            "PSH": self.psh,
            "DRUG_ALLERGY": self.drug_allergy,
            "FAMILY_HX": self.family_hx,
            "SOCIAL_HX": self.social_hx,
            "ROS": self.ros,
            "AYUSH_ASSESSMENT": self.ayush_assessment,
        }
        return section_map.get(section, SectionData())

    def add_conversation_message(self, role: str, content: str, category: str = "HPI"):
        """Add a message to the unified conversation history."""
        self.conversation_history.append({
            "role": role,
            "content": content,
            "turn": self.interview_turn_count,
            "category": category,
        })

    def update_filled_state(self, field_id: str, value: Any, confidence: float = 0.8):
        """Update the filled-state source of truth."""
        if value is not None and str(value).strip():
            self.filled_state[field_id] = {
                "value": value,
                "confidence": confidence,
            }

    def get_filled_summary(self) -> str:
        """Build a compact summary of all filled fields for LLM context."""
        if not self.filled_state:
            return "No information collected yet."

        parts = []
        if self.chief_complaint.value:
            parts.append(f"Chief Complaint: {self.chief_complaint.value}")
        if self.complaint_category:
            parts.append(f"Category: {self.complaint_category}")
        if self.patient_age:
            parts.append(f"Patient: {self.patient_age}y {self.patient_sex}")

        for field_id, entry in self.filled_state.items():
            if isinstance(entry, dict) and entry.get("value"):
                parts.append(f"{field_id}: {entry['value']}")

        return "\n".join(parts) if parts else "No information collected yet."

    def get_clinical_context_summary(self) -> str:
        """Legacy compat: Build a compact summary of everything known."""
        return self.get_filled_summary()

    def get_grouped_filled_data(self) -> dict[str, list[dict]]:
        """Group filled fields by category for the summary screen."""
        if not self.dynamic_schema:
            return {}

        groups: dict[str, list[dict]] = {}
        field_map = {f["id"]: f for f in self.dynamic_schema.get("fields", [])}

        for field_id, entry in self.filled_state.items():
            if not (isinstance(entry, dict) and entry.get("value")):
                continue
            field_spec = field_map.get(field_id, {})
            category = field_spec.get("category", "HPI")
            intent = field_spec.get("question_intent", field_id.replace("_", " "))

            groups.setdefault(category, []).append({
                "field_id": field_id,
                "question_intent": intent,
                "value": entry["value"],
                "confidence": entry.get("confidence", 0.0),
            })

        return groups

    def build_chronological_timeline(self) -> list[dict]:
        """
        Builds a unified, chronological timeline of patient history by extracting
        dates from document entities and the current conversation state.
        """
        timeline = []
        
        # 1. Add document extractions
        for doc in self.document_extractions:
            entities = doc.entities
            if isinstance(entities, dict):
                for category, items in entities.items():
                    if isinstance(items, list):
                        for item in items:
                            if isinstance(item, dict):
                                date = item.get("date", "Unknown Date")
                                name = item.get("name") or item.get("test") or "Unknown Entity"
                                details = ", ".join(f"{k}: {v}" for k, v in item.items() if k not in ["name", "test", "date"] and v)
                                timeline.append({
                                    "date": date,
                                    "source": f"Document ({doc.doc_type})",
                                    "category": category,
                                    "event": name,
                                    "details": details
                                })
        
        # 2. Add current encounter information
        current_date = "Current Encounter"
        for field_id, entry in self.filled_state.items():
            if isinstance(entry, dict) and entry.get("value"):
                timeline.append({
                    "date": current_date,
                    "source": "Conversation",
                    "category": "Current Interview",
                    "event": field_id.replace("_", " ").title(),
                    "details": str(entry["value"])
                })
                
        # Sort timeline
        def sort_key(item):
            d = item["date"]
            if d == "Current Encounter": return "9999-99-99" # Conceptually newest
            if d == "Unknown Date" or not d: return "0000-00-00" # Conceptually oldest
            return str(d)
            
        return sorted(timeline, key=sort_key)
