services:
  - type: web
    name: swasthyasync-patient-portal-api
    env: python
    rootDir: PatientPortal/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: OTP_PROVIDER
        value: "mock"
