"""
HOSPITAL & KIOSK KNOWLEDGE BASE FOR SWASTHYASYNC AI
Verified operational data for hospital navigation and kiosk assistance.
"""

HOSPITAL_PROFILE = {
    "name": "SwasthyaSync Healthcare Center",
    "accreditation": "NABH Accredited & ABDM Tier-1 Digital Hospital",
    "emergency_phone": "1800-123-4567 / 108",
    "opd_hours": "Monday to Saturday, 08:00 AM – 04:00 PM",
    "address": "Premises No. 1489, Sector V, Salt Lake, Kolkata, WB - 700091",
    "abdm_facility_id": "IN-WB-700091-01"
}

KIOSK_KNOWLEDGE = {
    "purpose": (
        "The SwasthyaSync Smart Kiosk is an automated pre-consultation intake station located at the OPD entrance. "
        "It collects and organizes patient medical history before they meet the doctor, saving up to 70% of intake time."
    ),
    "features": [
        "Conversational Voice Intake: Multi-lingual voice interview in English, Hindi, Bengali, and other regional languages powered by Sarvam AI.",
        "Optical Document Scanner: Scans previous doctor prescriptions and laboratory reports with high-precision OCR extraction.",
        "Baseline Vitals Capture: Records Blood Pressure, Pulse, SpO2, Temperature, Height, and Weight.",
        "Clinical Casesheet Generation: Synthesizes structured OPD casesheets, preliminary triage warnings, and ABDM QR codes for the attending doctor.",
        "Zero Doctor Replacement: The kiosk NEVER replaces the doctor; it only prepares an accurate clinical brief for the doctor's review."
    ],
    "what_to_do_after_kiosk": (
        "After completing your interview at the kiosk, you will receive your Token Slip. "
        "Proceed to the designated OPD waiting lounge. Your Token Number will be displayed on the digital queue screens outside the doctor's room."
    ),
    "document_upload_process": (
        "Place your previous paper prescription or blood test report flat inside the illuminated document scanning bay on the kiosk. "
        "The optical scanner will photograph the page, extract past medications and lab values, and link them to your consultation record."
    )
}

HOSPITAL_DEPARTMENTS = [
    {
        "name": "General Medicine",
        "room": "Room 101 – 104",
        "description": "Primary care for acute illnesses, fevers, chronic hypertension, diabetes management, and general systemic evaluations.",
        "consultants": "Dr. Sneha Roy (MD), Dr. Deepak Shankar Ray"
    },
    {
        "name": "Cardiology",
        "room": "Room 201 – 203",
        "description": "Heart disease, chest discomfort evaluation, ECG, echocardiography, lipid management, and cardiovascular rehabilitation.",
        "consultants": "Dr. Amitava Roy (DM Cardiology)"
    },
    {
        "name": "Nephrology",
        "room": "Room 205 – 206",
        "description": "Kidney health, chronic kidney disease (CKD), electrolyte imbalances, dialysis counseling, and creatinine monitoring.",
        "consultants": "Dr. D. S. Ray (MD, DNB Nephrology)"
    },
    {
        "name": "AYUSH / Integrative Medicine",
        "room": "Room 301 – 303",
        "description": "CCRAS-standardized Ayurvedic prakriti profiling, holistic lifestyle medicine, chronic metabolic management, and herbal therapies.",
        "consultants": "Vaidya R. K. Mishra"
    },
    {
        "name": "Orthopedics",
        "room": "Room 108 – 110",
        "description": "Bone fractures, joint pain, arthritis, spine care, and musculoskeletal rehabilitation.",
        "consultants": "Dr. Subhash Bose (MS Ortho)"
    },
    {
        "name": "Pathology & Diagnostics",
        "room": "Basement Level B1",
        "description": "Routine and specialized blood tests (CBC, LFT, KFT, HbA1c, Lipid profile), urine analysis, and rapid digital report delivery.",
        "timing": "07:30 AM – 06:00 PM"
    }
]

HOSPITAL_FAQS = [
    {
        "question": "How do I get a consultation token?",
        "answer": "You can get a token either at the SwasthyaSync Smart Kiosk at the hospital entrance by entering your ABHA ID or mobile number, or through the Patient Portal online."
    },
    {
        "question": "Can I view my past prescriptions on my phone?",
        "answer": "Yes! All prescriptions scanned at the kiosk or generated by your attending doctor are accessible under the 'History' tab on your SwasthyaSync Patient Portal."
    },
    {
        "question": "What is ABHA and why does SwasthyaSync ask for it?",
        "answer": "ABHA (Ayushman Bharat Health Account) is a 14-digit national health identity created by the Government of India under ABDM. It allows you to securely share and access your health records across hospitals nationwide."
    },
    {
        "question": "What should I do in a medical emergency?",
        "answer": "For immediate emergencies, call 108 or the hospital emergency line at 1800-123-4567, or proceed directly to the 24x7 Emergency Trauma Center at Gate 1."
    }
]

def search_hospital_knowledge(query: str) -> dict:
    """Retrieves matching hospital or kiosk knowledge snippets based on keywords."""
    q_low = query.lower()
    snippets = []
    
    if any(k in q_low for k in ["kiosk", "machine", "scan", "screen", "swasthya sync", "interview"]):
        snippets.append({
            "topic": "SwasthyaSync Smart Kiosk",
            "info": KIOSK_KNOWLEDGE["purpose"],
            "details": KIOSK_KNOWLEDGE["features"]
        })
    
    matched_depts = []
    for dept in HOSPITAL_DEPARTMENTS:
        if dept["name"].lower() in q_low or any(k in q_low for k in dept["description"].lower().split()):
            matched_depts.append(dept)
    
    if matched_depts:
        snippets.append({
            "topic": "Departments",
            "matches": matched_depts
        })
    elif any(k in q_low for k in ["department", "doctor", "specialist", "room"]):
        snippets.append({
            "topic": "All Available Departments",
            "departments": [d["name"] + " (" + d["room"] + ")" for d in HOSPITAL_DEPARTMENTS]
        })
        
    for faq in HOSPITAL_FAQS:
        if any(w in faq["question"].lower() for w in q_low.split() if len(w) > 3):
            snippets.append({"faq_question": faq["question"], "faq_answer": faq["answer"]})
            
    return {
        "hospital": HOSPITAL_PROFILE,
        "results": snippets
    }
